### ISSUE TITLE
I have successfully reversed CH551 ISP protocol.

### ISSUE THREAD

**Issue by rgwan** [Blinkinlabs/ch554_sdcc#1]
Here's my source code. But I'm not sure that whether or not it works on CH552/554.

https://github.com/rgwan/librech551

**Comment by rgwan** [comment]
BTW, original isp software will NOT working on WINE.

Because it have to communicate with CH375 driver.

**Comment by cibomahto** [comment]
Very cool! I'll try to test it out with a CH554 soon. Would be great to have a fully open solution for this chip!

**Comment by rgwan** [comment]
Please try out WIP branch, master branch doesn't support other chip id, because I hardcoded 0x51 for CH551.
