### ISSUE TITLE
My CH544 is a Bootloader 2.31 ...

### ISSUE THREAD

**Issue by RandoSY** [Blinkinlabs/ch554_sdcc#12]
I'm stuck on Linux today ... wondering about this error.
rasyoung@vic2016:~/code_test/8051/wch/ch554_sdcc/examples/pwm$ sudo make flash
wchisptool -f pwm.bin -g
Error while bulking in: LIBUSB_ERROR_OVERFLOW
Libre CH551 Flasher 2018
The chip id 0xFFFFFFD0 is currently not support in this program

Do you know fix for this ? Thanks for excellent postings!

**Comment by cibomahto** [comment]
Oh- that's probably better to ask in the librech551 project here:
https://github.com/rgwan/librech551/issues

There might be a replacement here:
https://github.com/rgwan/librech551/issues/11

We bought a large number of the old CH554 parts, and never ran out, so I haven't tried the new bootloader :-(.

**Comment by RandoSY** [comment]
Hi Matthew,

Thanks! will do ...

Randy
