### ISSUE TITLE
default CODE_SIZE should be 14kB (0x3800)

### ISSUE THREAD

**Issue by nerdralph** [Blinkinlabs/ch554_sdcc#16]
https://github.com/Blinkinlabs/ch554_sdcc/blob/master/examples/Makefile.include#L24

The specs for the CH554 state, [14KB Code Flash 2KB BootLoader](http://www.wch.cn/products/CH554.html).  I've tested on a CH552T, and get verify errors when I try to upload more than 14kB.

The specs for the CH551 state, "10KB Code Flash 2KB BootLoader", but I've been able to upload 12kB before I get verify errors on the CH551.

**Comment by cibomahto** [comment]
Ah, that makes sense. Want to make a pull request for it?

**Comment by nerdralph** [comment]
OK, I'll fork and update, then make a pull request.
