### ISSUE TITLE
Is it possible to rewrite the description without unnecessary words?

### ISSUE THREAD

**Issue by selevo** [Blinkinlabs/ch554_sdcc#18]
Like, now let's compile and oops nothing happened!
These superfluous words, expressions and actions are very annoying, because at least they spend time.

I would understand if it was some kind of novel or other literary adventure.
But I think people coming here hope to quickly connect everything and make everything work right away.

Without experimentation or other adventures.
---
Thank's

**Comment by nerdralph** [comment]
I think there is nothing wrong with the tutorial form, and for some beginners it's probably better than traditional documentation.
