### ISSUE TITLE
reconsider 24Mhz for USB CDC

### ISSUE THREAD

**Issue by nerdralph** [Blinkinlabs/ch554_sdcc#26]
The datasheet is confusing about what voltages are supported at different clock speeds and temperatures.  TA32M states >28MHz is supported in the range of -20C to 70C vs <28MHz is OK from -40C to 85C.  Then in table 18.4, Fsys at 24M is specified as requiring 4.4V.  I think 24M is safe with VCC >= 3V3 at normal temperature ranges.
For the USB CDC example, where the MCU is most likely powered from VBUS (USB 5V), in which case 24M should be safe over the full temperature range.
The benefit of 24M over 16M is much more accurate UART timing at high speeds.  At 16M, the counter reload value for 115.2kbps is 9 vs an ideal value of 8.68, making the timing 3.5% slow.  At 24M, the reload value will be 13 vs an ideal of 13.02, making it only 0.16% fast.

**Comment by cibomahto** [comment]
A faster clock speed would be great! Most of the designs I've made with the CH554 interface with 3.3V peripherals, so I have to run them at the lower voltage. It makes sense to use 5V for the reasons you mention though.

In this case, we're talking about the default frequency, right? I'm ok with setting that to a higher value, I can make a board specific define for the ones I have.

**Comment by nerdralph** [comment]
Yes, I'm just talking about the default.  And as I mentioned above, 24Mhz at 3.3V is supported in the range of -20C to 70C.

**Comment by cibomahto** [comment]
Thanks!

**Comment by nerdralph** [comment]
You were right about 24MHz not working well at 3V3.
https://github.com/DeqingSun/ch55xduino/issues/28

I'd still suggest leaving the default speed at 24MHz, perhaps with a comment in the CDC example to change it to 16MHz when the MCU is powered at 3V3.

**Comment by cibomahto** [comment]
Ah, oh well! Sure, a note sounds like a good idea.
