### ISSUE TITLE
ws2812 example doesn't work with default clock setting

### ISSUE THREAD

**Issue by buttim** [Blinkinlabs/ch554_sdcc#32]
I had to change FREQ_FSYS in Makefile.include to 12000000 to make it work, otherwise no LED in the strip lights on. Tested with a ws2812 24 LED ring and a 72 LED strip

**Comment by cibomahto** [comment]
Thanks for reporting- it's likely that the default frequency was 12MHz when this example was last tested!

**Comment by jjmz** [comment]
I just noticed that max. system frequency at 3.3V is 16Mhz : I spent much time trying to have the Blink example work before trying to reduce FREQ_SYS... So the problem might be related to the CH554 board you are using (I have an Electrodragon CH554, where the default config is to use 3.3V)

**Comment by buttim** [comment]
Same board here. Now we fully understand the problem. Thanks!
