### ISSUE TITLE
Software i2c

### ISSUE THREAD

**Issue by DurandA** [Blinkinlabs/ch554_sdcc#4]
Is there any plan to add software i2c support?

To the best of my knowledge, the CH554 doesn't have hardware i2c support and the official SDK doesn't provide a software implementation.

**Comment by cibomahto** [comment]
Looks like there is an implementation in this example:
https://github.com/Blinkinlabs/ch554_sdcc/blob/master/examples/usb_device_cdc_i2c/firmware/i2c.h
https://github.com/Blinkinlabs/ch554_sdcc/blob/master/examples/usb_device_cdc_i2c/firmware/i2c.c

Would be good to make a standalone example for the I2C part!

**Comment by DurandA** [comment]
Thank you for pointing it!
