### ISSUE TITLE
Chinese characters

### ISSUE THREAD

**Issue by mumbaiverve** [Blinkinlabs/ch554_sdcc#43]
Hello good people,
Not an issue with SDCC or CH554 per se , but ...
I downloaded the SDCC source from the blinkinlabs repo. When I open the code with VScode, i am able to see the chinese comments which I am able to translate with google.
when I download the code repo from the WCH website (for Keil) the chinese comments are not rendered properly. Is there any advice on how to get the comments in a translatable format ?
I am trying to use CH554 as a logger with a USB pen drive. I think udrive is still not ported to SDCC.
TIA

**Comment by mumbaiverve** [comment]
I managed to solve the issue. In VSCODE at the bottom there is an encoding selection. I clicked on the UT-8 and it gave me an option to select Chinese encoding. 
Sorry if this thread offends someone as irrelevant, you may delete it. I am new to github.

**Comment by cibomahto** [comment]
And you're correct that the pen drive example isn't ported- WCH only provides an object file for the fat32 library, which unfortunately isn't compatible with SDCC. It would be cool if you figured something out for that!
