### ISSUE TITLE
Is it compatible with ch559?

### ISSUE THREAD

**Issue by JoeHo8051** [Blinkinlabs/ch554_sdcc#49]
The other ch559 sdcc lib has some big issues, wondering if this could work on ch559

**Comment by cibomahto** [comment]
Good question- you'd need to compare the datasheets to be sure. I suspect that the core is quite similar, however some of the peripherals will likely be different. Apologies that I can't help more than that.

**Comment by JoeHo8051** [comment]
Thank you very much , I am to create a branch of this lib to make it compatible with CH559
