### ISSUE TITLE
S_FILES should be C_FILES in README.md

### ISSUE THREAD

**Issue by DurandA** [Blinkinlabs/ch554_sdcc#5]
There is a minor issue in the readme where `S_FILES` should be `C_FILES`:
https://github.com/Blinkinlabs/ch554_sdcc/blob/05ddb791ae77e27416b6bb6993d62a59aab175f4/README.md#L87

**Comment by cibomahto** [comment]
Good call. Fixed here: 3db082d0ea9636544a88827f152b8f70306c050c
